### ISSUE TITLE
hls compatibility 

### ISSUE THREAD

**Issue by fkoteam** [martinbjeldbak/acestream-http-proxy#15]
I'm using  https://github.com/ValdikSS/aceproxy and it's great despite it has no updates since 2015. 
Now I'm ready to move forward the new decade. This project has hls compatibility?
Thank you!

**Comment by martinbjeldbak** [comment]
It'll support anything the latest https://docs.acestream.net/products/#linux supports. Do you have an example of an HLS stream so  I can test?

**Comment by fkoteam** [comment]
sorry, maybe I am misunderstanding the way acestream works. Is it possible to proxy anything as hls? Maybe natively or reencoding with FFmpeg. Or is it only possible as original stream is encoded?
Thank you!!

**Comment by martinbjeldbak** [comment]
All good! I did a bit of reading and it actually does look like the AceStream engine (which this is just a wrapper around) supports outputting to HLS https://docs.acestream.net/en/developers/start-playback/#output-format

You should be able to test this by using the below command

1. run engine:
    ```console
    docker run -t -p 6878:6878 ghcr.io/martinbjeldbak/acestream-http-proxy
    ```

2. open media player with HLS url
    ```
    http://localhost:6878/ace/manifest.m3u8?id=dd1e67078381739d14beca697356ab76d49d1a2
    ```

I just tested on a couple of random AceStream IDs in VLC PLayer and it seems to work quite well! Is this what you're after?

I'm working on some updates in #16 to make this a bit smoother, it will be released as 2.0 due to breaking change in port to make it a bit more user friendly. Thanks for the suggestion!!

**Comment by fkoteam** [comment]
It would be great if the stream is playable in Firefox or Chrome. I'll try! Thank you very much!!

**Comment by martinbjeldbak** [comment]
You may need to use a plugin for firefox/chrome to play natively, but should work. Let me know how you go!

**Comment by fkoteam** [comment]
I also had issues in an ARM64, so finally I'd  installed acestream directly and it works as you've mentioned.
Thank you!
