### ISSUE TITLE
Update acestream version

### ISSUE THREAD

**Issue by DonTomate24** [martinbjeldbak/acestream-http-proxy#20]
Hello,

In Spain we are experiencing some connection blocks by the ISP when approximately 15 minutes are played. To solve it, the acestream team updated the program, solving the blockages starting from version 3.2.0

The container uses version 3.1.75rc4, so we are still experiencing these connection hangs when using it. Would upgrading to version 3.2.0 or higher be possible? Currently the latest version released by acestream is 3.2.3

Greetings and thanks!

**Comment by fkoteam** [comment]
i've been using this project, but I don't understand the advantages since you can install acestream on linux and play the streams after opening ports.

**Comment by martinbjeldbak** [comment]
I didn't realise there was a new AceStream release thanks for the reminder @DonTomate24. First time in a long time 😄  and I see they also support Python 3.10 now, awesome. Sure, I will work to update the Docker image. Should be updated in a couple of days, will let you know here when ready.

Alternatively you are more than welcome to raise a pull request updating this and I'll happily review. Will also allow you to test your connection blocks.

As far as the advantage of this project @fkoteam is that it simply wraps up the installation and dependency issues that may arise from installing acestream directly on linux. If you have Docker, that's all you need to get the application running. hope that makes sense!

**Comment by litio2001** [comment]
@martinbjeldbak take a look at this user's update: https://github.com/blaise-io/acelink

**Comment by martinbjeldbak** [comment]
Hi @DonTomate24 apologies on delay but I have just released [v2.1.0](https://github.com/martinbjeldbak/acestream-http-proxy/releases/tag/v2.1.0) bundling the latest AceStream version - can you see if this fixes it?

@litio2001 thanks for sharing this, looks really cool! I hadn't seen it before. I unfortunately don't use mac but otherwise would definitely install this on main pc :) could definitely incorporate some improvements from this project's Dockerfile too - the healthcheck and web player are impressive

**Comment by martinbjeldbak** [comment]
Closing for now, please message here on any troubles and ill reopen if needed cheers
